postgresql:
  image: postgres:10.1
  imagePullPolicy: IfNotPresent
  database: postgres
  username: postgres
  password: mypassword
  port: 5432
  replicas: 1
  storage:
    size: 10Gi
    
resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 250m
    memory: 1Gi

# databaseNames:
#   - db1
#   - db2
#   - db3

# userNames:
#   - user1
#   - user2
#   - user3

# hooks:
#   preStart:
#     - name: create-databases
#       manifest: |
#         #!/bin/bash
#         set -euo pipefail

#         for db_name in "${databaseNames[@]}"; do
#           psql -U postgres -c "CREATE DATABASE $db_name;"
#         done

#         for user_name in "${userNames[@]}"; do
#           psql -U postgres -c "CREATE USER $user_name WITH PASSWORD '${user_name}password';"
#           psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE ${postgresqlDatabase} TO $user_name;"
#         done

