apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "elasticsearch.fullname" . }}
  labels:
    app: {{ template "elasticsearch.name" . }}
spec:
  replicas: {{ .Values.elasticsearch.replicas }}
  selector:
    matchLabels:
      app: {{ template "elasticsearch.name" . }}
  serviceName: {{ template "elasticsearch.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "elasticsearch.name" . }}
    spec:
      containers:
      - name: elasticsearch
        image: {{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}
        env:
        - name: cluster.name
          value: {{ .Values.elasticsearch.clusterName }}
        - name: discovery.seed_hosts
          value: "{{ .Release.Name }}-0.{{ template "elasticsearch.fullname" . }}.headless.{{ .Release.Namespace }}.svc.cluster.local:9300,{{ .Release.Name }}-1.{{ template "elasticsearch.fullname" . }}.headless.{{ .Release.Namespace }}.svc.cluster.local:9300,{{ .Release.Name }}-2.{{ template "elasticsearch.fullname" . }}.headless.{{ .Release.Namespace }}.svc.cluster.local:9300"
        - name: cluster.initial_master_nodes
          value: "{{ .Release.Name }}-0,{{ .Release.Name }}-1,{{ .Release.Name }}-2"
        - name: ES_JAVA_OPTS
          value: "-Xms{{ .Values.elasticsearch.heapSize }} -Xmx{{ .Values.elasticsearch.heapSize }}"
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: data
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: {{ template "elasticsearch.name" . }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
