apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "postgresql.fullname" . }}"
  labels:
    app: "{{ include "postgresql.fullname" . }}"
    release: "{{ include "postgresql.fullname" . }}"
type: Opaque
data:
  username: {{ .Values.postgresql.username | b64enc | quote }}
  password: {{ .Values.postgresql.password | b64enc | quote }}