apiVersion: v2
appVersion: 5.0.0
dependencies:
- name: common
  repository: https://keshavprasadms.github.io/sunbird-helmchart-templates
  version: 0.1.0
- name: user_access_keys
  repository: https://keshavprasadms.github.io/sunbird-helmchart-templates
  version: 0.1.0
description: A helm chart for common opa policies
name: common_opa_policies
type: application
version: 0.1.0
