replicaCount: 1

image:
  registry: docker.io
  repository: bitnami/cassandra
  tag: 4.0.0-debian-10-r0
  pullPolicy: IfNotPresent

cassandraUser:
  username: admin
  password: cassandra-password

initdbScripts:
  cassandra-setup1.cql: |
    CREATE KEYSPACE IF NOT EXISTS mykeyspace1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'};
    CREATE TABLE IF NOT EXISTS mykeyspace1.mytable (id INT PRIMARY KEY, name TEXT);
  cassandra-setup2.cql: |
    CREATE KEYSPACE IF NOT EXISTS mykeyspace2 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'};
    CREATE TABLE IF NOT EXISTS mykeyspace2.mytable (id INT PRIMARY KEY, name TEXT);
  cassandra-setup3.cql: |
    CREATE KEYSPACE IF NOT EXISTS mykeyspace3 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'};
    CREATE TABLE IF NOT EXISTS mykeyspace3.mytable (id INT PRIMARY KEY, name TEXT);